### ISSUE TITLE
openssl issue while running code

### ISSUE THREAD

**Issue by aishwaryagm1999** [JRF63/DTLS-Example#1]
Hi I have installed OpenSSL and set all the paths in environment variables on my windows laptop. I get the following error when I run the code using cargo run.

Error: could not find native static library 'ssl', perhaps -L flag is missing
<img width="1175" alt="Screenshot 2022-05-04 at 2 42 02 PM" src="https://user-images.githubusercontent.com/55407808/166661695-4d70db05-8af5-4180-a0d2-00e3027bdea6.png">

The paths I have set:

<img width="515" alt="Screenshot 2022-05-04 at 2 44 04 PM" src="https://user-images.githubusercontent.com/55407808/166661742-10902e8b-9b15-4248-9feb-4200b1ae2892.png">
<img width="544" alt="Screenshot 2022-05-04 at 2 43 54 PM" src="https://user-images.githubusercontent.com/55407808/166661761-d82929ad-d908-4e34-a31d-60694d80a6f8.png">

**Comment by JRF63** [comment]
It should be looking for `libssl` and not `ssl`. I suppose try to rename `libssl.lib` to `ssl.lib` in your `C:\OpenSSL-Win64\lib` folder?

Based on your output you're failing to build `openssl-sys` before even reaching this package. So.. this issue is hardly related to this repository don't you think? The `openssl` crate is maintained over [here](https://github.com/sfackler/rust-openssl). They're likely to be of better help.
